chat/urls.py
from django.urls import path, re_path

from .views import ChannelDetailView, private_messages, DetailMs, Inbox

UUID_CANAL_REGEX = r'channel/(?P<pk>[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12})'
# app_name = 'worktions'
urlpatterns= [
    re_path(UUID_CANAL_REGEX, ChannelDetailView.as_view() ),
    path("chat/<str:username>", private_messages),
    path("ms/<str:username>", DetailMs.as_view(), name="detailms"),
    path("inbox", Inbox.as_view(), name="inbox")
]

worktions/urls.py
from django.contrib import admin
from django.urls import path, include
from Modules.Services import views as servicesViews
from django.contrib.auth.views import LoginView
from django.conf import settings
from django.conf.urls.static import static

# app_name = 'worktions'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('home', servicesViews.home, name="home"),
    path('register/', servicesViews.signUp, name="register"),
    path('post-service', servicesViews.postService,name="post-service"),
    path('profile',servicesViews.profile, name="profile" ),
    path('accounts/',include('django.contrib.auth.urls'), name="accounts/login"),
    path('edit_profile/', servicesViews.edit_profile,name="edit_profile"),
    path('delete_service/<id>', servicesViews.delete_service,name="delete_service"),
    path('edit_service/<id>', servicesViews.edit_service_template,name="edit_service_template"),
    path('edit_service', servicesViews.edit_service, name="edit_service"),
    path('analitica/', servicesViews.analiticaGrafica,name="analitica"),
    path('service/<int:pk>/', servicesViews.service_detail_view, name='service_detail'),
    path('user/profile/<str:pk>/', servicesViews.userDetail.user_detail_view, name='user-detail'),
    path('save_review/<int:sid>/', servicesViews.save_review, name='save_review'),
    path('', include('chat.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/models.py
import uuid
from django.db import models
from Modules.Services.models import User
from django.db.models import Count

class ModelBase(models.Model):
    id = models.UUIDField(default=uuid.uuid4, primary_key=True, db_index=True, editable=False)
    time = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

class ChannelMessage(ModelBase):
    channel = models.ForeignKey("Channel", on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()

class UserChannel(ModelBase):
    channel = models.ForeignKey("Channel", null=True, on_delete=models.SET_NULL)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

class ChannelQuerySet(models.QuerySet):

    def just_one(self):
        return self.annotate(num_users = Count("users")).filter(num_users=1)
    def just_two(self):
        return self.annotate(num_users = Count("users")).filter(num_users=2)
    
    def filter_by_username(self, username):
        return self.filter(userchannel__user__username=username)

class ChannelManager(models.Manager):   

    def get_queryset(self, *args, **kwargs):
        return ChannelQuerySet(self.model, using=self._db)

    def filter_ms_per_private(self, username_a, username_b):
        return self.get_queryset().just_two().filter_by_username(username_a).filter_by_username(username_b)
    
    def get_or_create_current_user_channel(self, user):
        qs = self.get_queryset().just_one().filter_by_username(user.username)
        if qs.exists():
            return qs.order_by("time").first(), False
        channel_obj = Channel.objects.create()
        UserChannel.objects.create(user= user, channel=channel_obj)
        return channel_obj, True
    
    def get_or_create_channel_ms(self, username_a, username_b):
        qs = self.filter_ms_per_private(username_a, username_b)
        if qs.exists():
            return qs.order_by("time").first(), False
        try:
            user_a =User.objects.get(username=username_a)
        except User.DoesNotExist:
            return None, False
        
        try:
            user_b =User.objects.get(username=username_b)
        except User.DoesNotExist:
            return None, False
        
        if user_a == None or user_b == None:
            return None, False
        
        channel_obj = Channel.objects.create()
        user_channel_a = UserChannel(user=User.objects.get(username=username_a), channel= channel_obj)
        user_channel_b = UserChannel(user= User.objects.get(username= username_b), channel= channel_obj)
        UserChannel.objects.bulk_create([user_channel_a, user_channel_b])
        return channel_obj, True


class Channel(ModelBase):
    users = models.ManyToManyField(User, blank=True, through=UserChannel)
    objects = ChannelManager()

chat/forms.py
from django import forms

class FormMessage(forms.Form):
    mensaje = forms.CharField(widget=forms.Textarea(attrs={
        "class": "form_ms",
        "placeholder": "Escribe tu mensaje",
    }))

chat/views.py
from django.http import HttpResponse, Http404, JsonResponse
from django.shortcuts import render
from django.views.generic import DetailView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from .forms import FormMessage
from .models import * 
from django.views.generic.edit import FormMixin

class Inbox(View):
    def get(self, request):
        inbox = Channel.objects.filter(userchannel__user__in=[request.user.id])

        context = {
            "inbox":inbox
        }

        return render(request, 'inbox.html', context)
    
class ChannelFormMixin(FormMixin):
    form_class = FormMessage
    # success_url = "./"

    def get_success_url(self):
        return self.request.path

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            raise PermissionDenied
        
        form = self.get_form()
        if form.is_valid():
            channel = self.get_object()
            user= self.request.user
            message = form.cleaned_data.get("mensaje")
            channel_obj = ChannelMessage.objects.create(channel = channel, user= user, text=message )
            # if request.is_ajax():
            #     return JsonResponse({'mensaje': channel_obj.text,
            #                          'username': channel_obj.user.username},
            #                          status = 201)
            return super().form_valid(form)
        else:
            # if request.is_ajax():
            #     return JsonResponse({'error': form.errors},
            #                          status = 400)
            return super().form_invalid(form)



class ChannelDetailView(LoginRequiredMixin, ChannelFormMixin, DetailView):
    template_name = 'channel_detail.html'
    queryset = Channel.objects.all()

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        obj = context['object']
        print(obj)

        # if self.request.user not in obj.users.all():
        #     raise PermissionDenied

        context['is_channel_member'] = self.request.user in obj.users.all()

        return context

class DetailMs(LoginRequiredMixin, ChannelFormMixin, DetailView):
    template_name = 'channel_detail.html'
    
    def get_object(self, *args, **kwargs):
        username = self.kwargs.get("username")
        my_username = self.request.user.username
        channel, _ = Channel.objects.get_or_create_channel_ms(my_username, username)

        if username == my_username:
            my_channel, _ = Channel.objects.get_or_create_current_user_channel(self.request.user)
            return my_channel
        if channel == None:
            raise Http404

        return channel

def private_messages(request, username, *args, **kwargs):
    if not request.user.is_authenticated:
        return HttpResponse('Prohibido')
    
    my_username = request.user.username
    channel, created = Channel.objects.get_or_create_channel_ms(my_username, username)
    
    if created: 
        print("Si, fue creado")
   
    channel_users = channel.userchannel_set.all().values("user__username")
    print(channel_users)
    channel_message = channel.channelmessage_set.all()
    print(channel_message.values("text"))
    return HttpResponse(f"Nuestro Canal - {channel.id}")

chat/templates/channel_detail.html
<style>
    *{
        margin: 0;
        padding: 0;
    }
    #ms_container{
        width: 100%;
        background: #12172d;
        height: calc(70vh);
        margin: 5px 0;
        overflow-y: auto ;   
    }

    .div_ms{
        margin: 1.2rem auto;
        width: 45%;
        padding: 0.2rem 0.6rem 0.2rem 0.6rem;
    }

    .div_main{
            width: 50%;
            height: 30px auto ;
            margin: 30px 25% ;
            background: #050d21;
            color: white;
    }
    .my_mss{
        margin-right: 5px;
        background-color: #477eff;
        color: white;
        border-bottom-left-radius:16px ;
        border-top-left-radius:16px ;
        border-top-right-radius:16px ;
    }
    .your_ms{
        background: #576c99;
        color: white;
        margin-left: 5px;
        border-bottom-right-radius:16px ;
        border-top-left-radius:16px ;
        border-top-right-radius:16px ;
    }

    .div_form_ms{
        width: 100%;
        margin-top: 5px;
        margin-bottom: 5px;
        margin-left: -1px;
        border: 1px solid rgb(11, 11, 11);
    }

    #id_mensaje{
       display: block; 
       padding: 6px 12px;
       margin-left: 1%;
       margin-right: 2%;
       width: 98%;
       min-width: 98%;
       max-width: 98%;
       height: 70px;
       min-height: 70px;
       max-height: 70px;
       box-sizing: border-box;
       font-size: 14px;
       color: black;
       border: 1pz solid green;
       border-radius: 4px;
    }

    .btn_send{
        background: #477eff;
        color: aliceblue;
        padding: 5px 10px;
        border-radius: 5px;
        border: none;
        outline: none;
        width: 150px;
        cursor: pointer;
        display: block;
        margin: 10px auto;
        font-size: 13px ;
        transition: 0.3;
    }

    .form_ms{
        background-color: #cecccc;
        color: white;
    }
    #form_submit{
        color: white;
    }
    
</style>
{% extends './base.html' %}
{% block content %}
<body style="background-color: #12172d;">
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    
    <div class="div_main">
            <h3>Identificador del canal: {{ object.id}}</h3>
            <h1>Mensajes del canal</h1>
            <div id="ms_container">
                {% for message in object.channelmessage_set.all %}
                <div class="div_ms {% if request.user == message.user %}my_mss{% else %}your_ms {% endif %}">
                    <small>{{message.user}}</small>
                    <p>{{message.text}}</p>
                    <small>{{message.time}}</small>
                </div>                
                {% endfor %}
            </div >
            <div class="div_form_ms">
                <form id="form_submit" action="{{ request.path }}" method="POST">
                    {% csrf_token %}
                    <strong >{{form.as_p}}</strong>
        
                    <button type="submit" class="btn_send">Enviar</button>
                </form>
            </div>
    </div>
</body>

{% endblock %}
        
            
        <script>
            const msgForm = document.getElementById("form_submit")
            const msgContainer = document.getElementById("ms_container")

            
            msgForm.addEventListener("submit", (event) => {
                event.preventDefault()

                const targetDate = event.target
                const formData = new FormData(targetDate)

                const xhr = new XMLHttpRequest()

                const endpoint = msgForm.getAttribute("action")
                const method = msgForm.getAttribute("method")
                xhr.open(method, endpoint)

                xhr.responseType = 'json'

                xhr.setRequestHeader("HTTP_X_REQUESTED_WITH", "XMLHttpRequest")
		        xhr.setRequestHeader("X-Requested-With", "XMLHttpRequest")

                xhr.onload = () => {
                    console.log(xhr.status, xhr.response)

                    const responseData = xhr.response
                    let currentMessageHtml = msgContainer.innerHTML
                    currentMessageHtml += `<div class=''><b></b><p>${responseData.mensaje}</p></div>`                    msgContainer.innerHTML = currentMessageHtml
                    msgForm.reset()
                    // }else if(xhr.status == 400){
                    //     console.log(xhr.response)
                    // }else{
                    //     console.log(xhr.status, xhr.response)
                    //     alert("Ha ocurrido un error, intenta luego")
                    // }
                }

                xhr.send(formData)
            })
        </script>
    </body>
</html>

chat/templates/inbox.html
    <style>
        .div_main{
            width: 70%;
            margin: 0px 15% 90px ;
            height: 50px auto ;
            display: block;
            align-content: center;
        }

        .div_inbox{
            width: 90%;
            margin: 10px auto;
            background: #12172d;
            color: aliceblue;
            border-radius: 5px;
            border: 1px solid grey;
            padding: 5px;
        }

        body{
            background: whitesmoke;
        }

    </style>
    {% extends "base.html" %}   
    {% block content %} 
    <body style="background-color: #ebebed;">
        <div class="div_main">
            <br>
            <br>
            <br>
            <br>                       
            <br>
            <br>
            <br>
            <h1>
                Bienvenido {{ user }} a tus mensajes directos
            </h1>
            {% for inbox in inbox %}
            <div class="div_inbox">
                {% for second_user in inbox.userchannel_set.all  %}
                    {% if second_user.user == request.user %}
                    {% else %}
                        <a href="{% url 'detailms' second_user.user.username %}">
                            <strong>
                                {{second_user.user}}
                            </strong>
                            <br>
                            <small >({{inbox.channelmessage_set.count}}) Mensajes</small>
                        </a>
                    {% endif %}
                {% endfor %}
    
                {% if inbox.channelmessage_set.count != 0 %}
                    <div  class="div_ms_inbox">
                        {% with last_message=inbox.channelmessage_set.last %}
                        <p>Mensaje: {{last_message.text}}</p>
                        <p>Usuario: {{last_message.user}} </p>
                        {% endwith %}
                    </div>
                {% else %}
                <p>
                    No hay mensajes en tu inbox
                </p>
                {% endif %}
                
            </div>
            {% empty %}
            <h2>Inbox vacío</h2>
            {% endfor %}
        </div>
    </body>
    {% endblock %} 
        